Repository RyanMarcotte/Functional.Utilities, pull requests merged in 2020-10, with the labels that each got.

#9 Adds extension methods for Task wrapped Result and Option type assertions
  README.md
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions.Tests/OptionTypeAssertionsExtensionsTests.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions.Tests/ResultTypeAssertionsExtensionsTests.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/Extensions/OptionExtensions.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/Extensions/ResultExtensions.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions.csproj
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/FunctionalPrimitiveAssertions.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/OptionTypeAssertionsExtensions.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/OptionTypeAssertions_Obsolete.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/ResultTypeAssertionsExtensions.cs
Labels: documentation, enhancement

#11 Update README.md
  README.md
Labels: documentation

#8 Assertions for Functional.Unions (Union<...> and Task<Union<T...>>)
  README.md
  src/Functional.Primitives.FluentAssertions/README.md
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/Functional.Unions.FluentAssertions.Tests.csproj
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithEightTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithFiveTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithFourTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithSevenTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithSixTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithThreeTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.AdHocWithTwoTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithEightTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithFiveTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithFourTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithSevenTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithSixTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithThreeTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.DefinitionWithTwoTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.Models.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithEightTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithFiveTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithFourTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithSevenTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithSixTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithThreeTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskAdHocWithTwoTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithEightTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithFiveTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithFourTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithSevenTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithSixTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithThreeTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.Tests/UnionValueTypeAssertionsTests.TaskDefinitionWithTwoTypes.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.sln
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/AndUnionValueConstraint.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/AndUnionValueConstraintExtensions.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/Extensions/UnionExtensions.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.csproj
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions2.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions3.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions4.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions5.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions6.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions7.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/FunctionalUnionAssertions8.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions2.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions3.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions4.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions5.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions6.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions7.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertions8.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions2.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions3.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions4.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions5.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions6.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions7.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions8.cs
  src/Functional.Unions.FluentAssertions/README.md
Labels: documentation, enhancement

#13 Updates the public extensions to use the `Functional` namespace.
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions.csproj
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/OptionTypeAssertionsExtensions.cs
  src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions/ResultTypeAssertionsExtensions.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/AndUnionValueConstraintExtensions.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions.csproj
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions2.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions3.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions4.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions5.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions6.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions7.cs
  src/Functional.Unions.FluentAssertions/Functional.Unions.FluentAssertions/UnionValueTypeAssertionsExtensions8.cs
Labels: bug

#12 Functional.Primitives.SerilogExtensions library
  .travis.yml
  README.md
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/Functional.Primitives.SerilogExtensions.Tests.csproj
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/SerilogExtensionsTests.OptionAndResultDestructurePolicyTests.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/SerilogExtensionsTests.OptionDestructurePolicyTests.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/SerilogExtensionsTests.ResultDestructurePolicyTests.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/SerilogExtensionsTests.WeirdDestructurePolicyTests.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/SerilogExtensionsTests.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/_Infrastructure/LogEventCollectionAssertions.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.Tests/_Infrastructure/LogEventCollectionExtensions.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.sln
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.sln.DotSettings
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions.csproj
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/LoggerDestructuringConfigurationExtensions.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/OptionDestructurePolicy.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/OptionDestructurePolicyConfiguration.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/ResultDestructurePolicy.cs
  src/Functional.Primitives.SerilogExtensions/Functional.Primitives.SerilogExtensions/ResultDestructurePolicyConfiguration.cs
  src/Functional.Primitives.SerilogExtensions/README.md
Labels: documentation, enhancement
